image: node:18-alpine

stages:
  - install
  - lint
  - test
  # - build
  - sonar

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

before_script:
  - apk update && apk upgrade && apk add --no-cache chromium


install:
  stage: install
  script:
    - npm cache clear -f
    - npm cache verify
    - npm install --legacy-peer-deps 
  artifacts:
    paths:
      - /builds/dgtic-offshore/ecmca/ecmca-frontend/node_modules/

lint:
  stage: lint
  script:
    - npm install --legacy-peer-deps 
    - npm run lint
  needs: ["install"]
  allow_failure: true

test:
  stage: test
  script:
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm install -g @angular/cli
    - npm install --legacy-peer-deps 
    - npm install -D karma-sonarqube-reporter --legacy-peer-deps
    - npm install -D sonarqube-scanner --legacy-peer-deps
    - npm run test
  artifacts:
    paths:
      - /builds/dgtic-offshore/ecmca/ecmca-frontend/coverage/
    reports:
      junit:
        - /builds/dgtic-offshore/ecmca/ecmca-frontend/coverage/ecmca-frontend/junit.xml

# frontend-build:
#   stage: build
#   script:
#     - cd /builds/dgtic-offshore/ecmca/ecmca-frontend
#     - npm install -g @angular/cli
#     - npm ci --unsafe-perm
#     - node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --aot --configuration=production --source-map=false
#     - sed -i "s/TAG/$CI_COMMIT_TAG/g" dist/index.html
#     - cat dist/index.html
#   artifacts:
#     expire_in: 1 day
#     paths:
#       - /builds/dgtic-offshore/ecmca/ecmca-frontend/dist/
#   needs: ["test"]

  
sonar-frontend:
  stage: sonar
  image: ${CI_REGISTRY}/dep/library/ci-library/sonarsource/sonar-scanner-cli:4.6
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - ls -la /builds/dgtic-offshore/ecmca/ecmca-frontend/coverage/
    - >
      sonar-scanner 
      -Dsonar.projectKey=es.gva.ecmca:ecmca-frontend  
      -Dsonar.projectName="ECMCA FRONTEND"
      -Dsonar.javascript.lcov.reportPaths=/builds/dgtic-offshore/ecmca/ecmca-frontend/coverage/ecmca-frontend/lcov.info 
      -Dsonar.host.url=$SONAR_URL 
      -Dsonar.login=$SONAR_LOGIN
      -Dsonar.TOKEN=$SONAR_TOKEN
      -Dsonar.password=$SONAR_PASSWORD
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME 
      -Dsonar.sourceEncoding=UTF-8 
      -Dsonar.sources=/builds/dgtic-offshore/ecmca/ecmca-frontend
      -Dsonar.exclusions=node_modules/**,**/*.spec.ts,**/*.model.ts,**/*.directive.ts,**/*.interceptors.ts,**/*.const.ts,**/runtime/**/*.ts,**/spy/*.ts,**/*.module.ts,**/test-utils.ts
      -Dsonar.tests=/builds/dgtic-offshore/ecmca/ecmca-frontend -Dsonar.test.inclusions=**/*.spec.ts
  only:
    - develop
    - master
    - staging