image: node:18-alpine

stages:
  - install
#  - lint
  - test


install:
  stage: install
  script:
    - npm cache clear -f
    - npm cache verify
    - npm install --legacy-peer-deps 

.lint:
  stage: lint
  script:
    - npm install --legacy-peer-deps 
    - npm run lint
  needs: ["install"]

test:
  stage: test
  script:
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm install -g @angular/cli
    - npm install
    - npm run test


    