image: node:18-alpine

stages:
  - install
#  - lint
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

before_script:
  - apk update && apk upgrade && apk add --no-cache chromium


install:
  stage: install
  script:
    - npm cache clear -f
    - npm cache verify
    - npm install --legacy-peer-deps 
  artifacts:
    paths:
      - /builds/dgtic-offshore/ecmca/ecmca-frontend/node_modules/
  rules:
    - if: ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "staging")

.lint:
  stage: lint
  script:
    - npm install --legacy-peer-deps 
    - npm run lint
  needs: ["install"]
  rules:
    - if: ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "staging")

test:
  stage: test
  script:
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm install -g @angular/cli
    - npm install --legacy-peer-deps 
    - npm run test
  rules:
    - if: ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "staging")


    