image: node:16.14.2-alpine

stages:
  - install
  - lint


install:
  stage: install
  script:
    - npm cache clear -f
    - npm cache verify
    - npm install --legacy-peer-deps 

lint:
  stage: lint
  script:
    - npm run lint
  needs: ["install"]